### ISSUE TITLE
Add Yaml2Properties

### ISSUE THREAD

**Issue by ahelmy** [ahelmy/xdev#34]
**Is your feature request related to a problem? Please describe.**
Java developers mainly could use this feature.

**Describe the solution you'd like**
Add Yaml2properties command and UI and vice-versa

**Describe alternatives you've considered**
https://mageddo.com/tools/yaml-converter

**Comment by nerdxio** [comment]
Hello Eng Ali,

I'm interested in working on this issue. I've gone through the details, and I believe I can contribute to resolving it.  
Could you please provide more information or guidance on how to get started?

Thanks!

**Comment by ahelmy** [comment]
Hi @nerdxio ,
Thank you for your contribution, you have to fork the repo and work on it locally then open a pull request.
For development I mentioned in the readme how to start. If you need more information please just ask.
Thank you

**Comment by nerdxio** [comment]
I was wondering Which approach should I go with for the command structure?
1. **Have two commands:**
	- `yam2prop` for YAML to properties conversion.
	- `prop2yam` for properties to YAML conversion.
2. **Use a single command with flags:**
	- `convert --from=yam --to=prop` allowing users to specify the conversion direction.

**Comment by ahelmy** [comment]
I would recommend, `yaml2prop` and alias `y2p` and `prop2yaml` and alias `p2y`.
Thank you

**Comment by ahelmy** [comment]
Hi @nerdxio,
I have added a discord server for the project if you want to join in for further discussion. 
Thank you

**Comment by nerdxio** [comment]
Sure thing,
Thanks for the invite! I'll join
